[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#007bff"

# Disable file watching to prevent inotify limit issues
[fileWatcher]
type = "none"
